[theme]
base = "light"
primaryColor = "#3B825C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#272F4D"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false
maxMessageSize = 200
enableWebsocketCompression = false
timeout = 7200 